---
name: Arborist

"on":
  - create
  - delete
  - pull_request
  - push

permissions:
  content: write

jobs:
  arborist:
    name: Prune dead branches
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: run arborist
        uses: jhoblitt/arborist-action@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
